language: java
dist: xenial
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
script: lein do clean, test, install
deploy:
  provider: script
  script: lein deploy
  skip_cleanup: true
env:
  global:
  - secure: DjhqyLQR5gD73m0t1NT2C7TDg+BrBf/uGNuY8OM0Hl+cgWsQLE6WZM1Ampie45muM2lM9eVj7hEUNkmATSR5UbDEJso/gH2Q+Y2wUWmEJyzBsuogyjFKHRES1kKFEYldkGAVVD8EdaOw0x6kUNtp7Rxhz2PH8MsayhDxW9nePljJi0q2xhwfpago3S+QALU4ZKPzAL6+E3YAlD4jG/s2EuhOrkfZBUz/foupdFbMwmEiIYnw2cbNG31E52AOIZx1rN+vyqpsi+xGjEAuewsN6dmQKW6/Lj+3OLoc4FZUdWVeenA7kA9PpOv/eUlwCfoq/CaHWJewe75bszFkzk8yBF2zRegPoU6wDVprGTlOE38WyI4Yld0aG/5K6RgH/tQFF6rtFh7HNjmkdb8ckEpge+eugOeqKQVaOXVU9LcE7IGwV0RWbwgd0b9TwqPYvqxfl2PkNo2ch2WrQJ04soacnuEwBQQW79Z19j01cKilgK3aP1RU3vspZ6vAdx7rWNPNQh4c6Gy9+qKgyp28Y0/al1VRrw9wMhpR0zlIgvuzLrMFZJdvSmVoGtNlF52NhcLNbCmMfpmgztSYa0z88jsdG2qbxPdOJ9lM6EbhVM8utL1a2YT2mlA++LDsqxCwOsU/0/FjwCQYJnrwmElIGChXGUb+SgnHR+ev2MmIKB2+efI=
  - secure: COqwMoawVt0/kpMh8tfOGQsVyzLOusEIiu6b7gTh0TbgNtGMXeaxe9/PGtPbzEg+P3L6Y/GLi8jof4Mfp+EFCjm/NQZy/SLIEyFzUijgLFjXL2ZHuuT6emv9r4VSipfiyXiyMwvppDC8FXblNVqnFRaCYJmd8Kw0RyoOg8uP3sr5ISNQ1CQilevNfbRjoulQQkmdlZp7OKlEKtqXleyGuXBwXoGiWYKnc8s3NbSrsyWdt8Ls5PWdV+OrKi3DKAQ/xyw/WEe/UGjeK0N/o7IyDHMGMxft+bWMOHjcew212aLkZskaUuwEVGWNHNdBqkh08xr8K8CaT+IOWNpvuaNyfeChTM3KvLDKKLemPF0bSQQbYdwpQyvAFnj98VxLDR5dxa95tloJqElo03W+LAcu14ajZom5eT/OuAZt9txhtYOTgcgUi1Z8I6lesPH14a4diyTqepLaNq4Dp1lTSWwwQLhAEzGtaqKy73xEYk/NHibVpMhZzYVxSiUaduAWr3EY2DuKudTRi9ii8/qrlDX3ZMZARGB90/KV0ivnMFJOe4jNV+mNTWI/ukrC8QJVfuFhb2H9BcuWOv7J1syMV6B4af5G2Qzk7vhGaTa011z1lDO6B261SHNWNmW+6+uSEE+JQkodIj16A+EDZwdnUL5aYVF6x7g8knaWyx83MtH7uIY=
notifications:
  slack:
    rooms:
      secure: EA4svd0wLV362hvtVy1qilIw5A42AvEjNvEIAcTgXpZyNXMrfitnFEI0F7uyRmkPrUJDS/eGTFLlZYZEStwH+iMJzonlhsYu8Ef8/icLCV1oPzgVnYH+g95ShTyWwbzhfa1WxkQ94h/wZRtqnFTs9OQbJ22MOLuC1LMtMRSSP71JP0+/K11n3h9s+SrwVijzyLuKTybIIdnuWCN+S1uALWyHp9TMc/GoSJRl9Ff4DWmnihyWEWFg1YTtK8WBWjvDipxZGOxAUQbFrfWo1IodNxYmT9t9+Z1fUtQ06S55lNhody6+uzpi9UoMYiKv+ol4iUe0iLGpyUNKnAeXHOspLThiYIggs9IXmj7QlxGS5oHbroPxQ+sumaAkFoFyfoGSbZQO3ukKQcHRLbr15JK30IgoC5gwf3gZlEy2TncHDqV7HEryqgYCElD/Us7pwOgrOwLKW7Jojjmx2EYnsjfdPspJ6pl/RI7NYQhePwovG3HyD6fqy7yhfKaDI2ygUpAyCYjMC24ap/cYs8ko9mZ0CpFPZPZjgp3WTL244ROMQ4KHclAGC/oaw2S30OLQ5CTLrDJrzQjWjDQeieIE5eKrW2UmdS/r7CFDE0CSkEBwiuiU92GKolhBn/o2yCG8FSBeknMDHu4JioQCbAJBZyAZfFEzJEb7PUUq08PtA+GEsyM=
